# config/defaults.yaml
pdb_code: 6OIK
chain_id: A
path_length: 100000        # default selection (can be any integer)
email: ""

# leave empty to preview only; set to your real endpoint to POST
target_url: ""

# map your server’s expected field names
field_names:
  pdb_code: pdbcode
  pdb_file: pdbfile
  chain_id: chainid
  path_length: path_length
  email: email

# NEW: values shown in the List mode of the path-length selector
path_length_options:
  - 100000
  - 200000
  - 300000
  - 400000
  - 500000
  - 750000
  - 1000000
  - 2000000
  - 3000000
  - 4000000

branding:
  logo_url: "https://raw.githubusercontent.com/enesemretas/mcpath-colab/main/assets/mcpath_logo.png"
  logo_height: 96     # px
  logo_align: "left"  # "center", "left", or "right"
